name: MyAppToShowMySkills
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_form_builder: ^3.14.1
  flutter_screenutil: ^1.1.0
  form_field_validator: ^1.0.1
  material_design_icons_flutter: ^4.0.5755
  image_picker: ^0.6.7+12
  #A flutter package for showing a country code selector.
  country_code_picker: ^1.6.2
  # A set of utilities that allow you to easily consume a Redux Store to build Flutter Widgets.
  flutter_redux: ^0.8.2

  # Redux Remote Devtools support for Dart and Flutter.
  redux_remote_devtools: ^3.0.0

  # A powerful Http client for Dart, which supports Interceptors, Global configuration, FormData,
  # Request Cancellation, File downloading, Timeout etc.
  dio: ^3.0.8

  # A dio transformer especially for flutter, by which the json decoding will be in background with [compute] function.
  dio_flutter_transformer: ^3.0.2

  # A simple dependency injection plugin for Flutter and Dart.
  flutter_simple_dependency_injection: ^1.0.2+1

  # Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based
  # solution is used in Android.
  flutter_secure_storage: ^3.3.1+1
  shared_preferences: ^2.0.5
  redux_thunk: ^0.4.0
  flushbar: ^1.10.2
  #A Flutter staggered grid view which supports multiple columns with rows of varying sizes.
  flutter_staggered_grid_view: ^0.3.2
  like_button: ^1.0.3
  flutter_spinkit: "^4.1.2"
  flare_flutter: ^1.7.1
  #google maps
  google_maps_flutter: ^1.0.10
  #for maps
  geolocator: ^6.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^3.2.3

# Classes and helper functions that support JSON code generation via the json_serializable package.
  json_annotation: ^3.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# Tools to write binaries that run builders.
  build_runner: ^1.10.1
  build_resolvers: ^1.3.11
  build_runner_core: ^5.0.0  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash_screen.jpg
    - assets/flr/robot-no-data.flr
    - assets/flr/roket.flr
    - assets/flr/229_Design Thinking.flr
    - assets/flr/watch_cog.flr
    - assets/flr/programmer_fork.flr
    - assets/flr/keep purple.flr
    - assets/flr/Calendario.flr
    - assets/flr/to do done.flr
    - assets/flr/infinite-list.flr
    - assets/flr/settings.flr
    - assets/flr/Provider Bounce.flr
    - assets/flr/Robot Animation.flr
    - assets/flr/message.flr
    - assets/flr/email_sending_progress_2.flr
    - assets/flr/maps_loader.flr
    - assets/flr/go to game.flr
    - assets/flr/login_door.flr
    - assets/flr/NewsMedia.flr




    - assets/images/dashboard/calendar.png
    - assets/images/dashboard/festival.png
    - assets/images/dashboard/food.png
    - assets/images/dashboard/map.png
    - assets/images/dashboard/notification.png
    - assets/images/dashboard/setting.png
    - assets/images/dashboard/todo.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
